version: '3.7'

services:
  somfy2mqtt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: somfy2mqtt
    image: somfy2mqtt:latest
    deploy:
      placement:
        constraints:
          - "node.labels.type==ctrl"
          - "node.labels.location==dronten"
    restart: always
    tty: true
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
      - PIGPIO_ADDR=10.0.8.2
      - PIGPIO_PORT=8888
      - PIGPIOD_ARGS=-e -m -a
    networks:
      - somfy
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/mem
      - /dev/vcio
      - /dev/gpiomem
    volumes:
      - /sys:/sys
      - /srv/docker/data/somfy2mqtt/log:/opt/somfy/log
      - /srv/docker/data/somfy2mqtt/config:/opt/somfy/config
    ports:
     - 8880:80
     - 8443:443
networks:
  somfy:
