version: '3.7'

services:
  somfy2mqtt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: somfy2mqtt
    image: somfy2mqtt:latest
    deploy:
      placement:
        constraints:
          - "node.labels.type==ctrl"
          - "node.labels.location==dronten"
    restart: always
    tty: true
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
      - DSMR_SERIAL=/dev/ttyUSB3
      - DSMR_MQTT_URL=mqqt-smurf.server.dronten.red-home.nl
      - DSMR_MQTT_PORT=1883
      - GPIO_UP=
      - GPIO_DOWN=
      - GPIO_MENU=
      - GPIO_PROG=
    networks:
      - somfy
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/mem
      - /dev/vcio
      - /dev/gpiomem
    volumes:
      - /sys:/sys
      - /srv/docker/data/somfy2mqtt/log:/opt/somfy/log
      - /srv/docker/data/somfy2mqtt/config:/opt/somfy/config
networks:
  somfy:
